### ISSUE TITLE
Not sure if it's the extension or the site but folding my arrays is borked, and it's probably my fault 🤦‍♂️

### ISSUE THREAD

**Issue by dmattox10** [Exifly/codeishot_vscode_ext#2]
This chunk of code should be foldable in 4 places, but folding the first array even though it's properly terminated results in all folded into the first in the view, I specifically want to fold the first three I spread inside the fourth one at the end (the language we speak sometimes....) at this link made with the extension: 
I'm surmising that it's because I'm one of those evil devs that doesn't use semicolons because they are ugly 👀
https://codeishot.com/2UNDx4rK

Images 
![addpoint-jsx](https://github.com/Exifly/codeishot_vscode_ext/assets/2966689/526f5e71-c28b-465f-8563-7883a4e99a03)
of angst:

![addpoint-jsx-2](https://github.com/Exifly/codeishot_vscode_ext/assets/2966689/8db27fa0-023b-4b5e-93de-335fcda2187f)

**Comment by FlavioAdamo** [comment]
Hi! First of all, thank you so much for the report.

This is just an indentation problem. If you remove the additional space in line 80, you should be able to fold it into 4 pages:
<img width="801" alt="image" src="https://github.com/Exifly/codeishot_vscode_ext/assets/46765573/698ee729-acdb-4209-bb7a-5dc6514fa575">

When logged in, you can edit the snippet on the "collection" page. 😊

By the way, we noticed that your snippet has no highlights since Codeishot does not recognize JSX as a "supported" language. So we just added it 😄 

If you reupload the code through the website or the VSCode extension, you should now be able to see the correct highlights!

**Comment by dmattox10** [comment]
Hmmmm. I tried again, couldn't find any spacing or indentation issues on line 80, then I realized mine is offset because I highlighted 260 lines of data out of a component closer to double at 408, line 80 is the beginning of energy range and I couldn't find anything different about that line or the one on either side, but your screenshot  looks like line 1 ends *without* a ']' ?? I played with line 80 after it got to your editor and that looked normal too? But here's the same:

https://codeishot.com/30ggh3Hh

**Comment by dmattox10** [comment]
It's good to close issues but it still does it lol..

**Comment by FlavioAdamo** [comment]
Hi @dmattox10 !
Sorry, but I had a busy day. Don't take this personally, please.

Keep in mind that the editor is powered by Monaco Editor, the same one used in VSCode. After putting your code into a beautifier, I got the correctly formatted version -> https://codeishot.com/42ObGXly

If this does not solve your problem, I'm totally open to having a talk with you :)
